export const CATEGORIES = [
  { id: 'plumber', label: 'Plumber', labelHi: 'प्लंबर', icon: 'Droplets' },
  { id: 'electrician', label: 'Electrician', labelHi: 'इलेक्ट्रीशियन', icon: 'Zap' },
  { id: 'painter', label: 'Painter', labelHi: 'पेंटर', icon: 'Palette' },
  { id: 'carpenter', label: 'Carpenter', labelHi: 'बढ़ई', icon: 'Hammer' },
  { id: 'cleaner', label: 'Cleaner', labelHi: 'सफाई कर्मचारी', icon: 'Brush' },
  { id: 'construction', label: 'Construction', labelHi: 'निर्माण मजदूर', icon: 'HardHat' },
  { id: 'farm', label: 'Farm Labor', labelHi: 'खेत मजदूर', icon: 'Sprout' },
  { id: 'driver', label: 'Driver', labelHi: 'ड्राइवर', icon: 'Car' },
];

export const TRANSLATIONS = {
  en: {
    heroTitle: "Find Trusted Help Nearby",
    heroSub: "Connecting rural communities with skilled local workers.",
    searchPlaceholder: "What help do you need?",
    categories: "Popular Services",
    nearbyWorkers: "Workers Near You",
    viewProfile: "View Profile",
    bookNow: "Book Now",
    available: "Available Now",
    offline: "Currently Busy",
    rating: "Rating",
    reviews: "Reviews",
    hourly: "per hour",
    bookingTitle: "Book Service",
    schedule: "Schedule Delivery",
    confirmBooking: "Confirm Booking",
    myBookings: "My Bookings",
    home: "Home",
    becomeWorker: "Join as Worker",
    login: "Login",
    logout: "Logout",
    aiSupport: "AI Recommendation",
    askAi: "Tell us your problem, and we'll suggest someone.",
    aiThinking: "Finding the best match for you...",
    language: "Language",
  },
  hi: {
    heroTitle: "आस-पास के भरोसेमंद मजदूर खोजें",
    heroSub: "ग्रामीण समुदायों को कुशल स्थानीय श्रमिकों से जोड़ना।",
    searchPlaceholder: "आपको किस काम में मदद चाहिए?",
    categories: "लोकप्रिय सेवाएं",
    nearbyWorkers: "आपके आस-पास के मजदूर",
    viewProfile: "प्रोफ़ाइल देखें",
    bookNow: "अभी बुक करें",
    available: "अभी उपलब्ध",
    offline: "अभी व्यस्त",
    rating: "रेटिंग",
    reviews: "समीक्षाएं",
    hourly: "प्रति घंटा",
    bookingTitle: "सेवा बुक करें",
    schedule: "समय तय करें",
    confirmBooking: "बुकिंग की पुष्टि करें",
    myBookings: "मेरी बुकिंग",
    home: "मुख्य",
    becomeWorker: "मजदूर के रूप में जुड़ें",
    login: "लॉगिन करें",
    logout: "लॉगआउट",
    aiSupport: "एआई सिफारिश",
    askAi: "हमें अपनी समस्या बताएं, और हम किसी का सुझाव देंगे।",
    aiThinking: "आपके लिए सबसे अच्छा विकल्प खोजा जा रहा है...",
    language: "भाषा",
  }
};
